<?php
/** @var \Magento\Framework\Escaper $escaper */
$ajaxUrl = $block->getUrl('avanti-estimator/ajax/estimate');
?>
<div class="shipping-estimator" data-estimator='{"ajaxUrl":"<?= $escaper->escapeUrl($ajaxUrl) ?>"}'>
    <strong class="title-text"><?= $escaper->escapeHtml(__('Calculate shipping')) ?>:</strong>

    <div class="field">
        <label class="label-input"><?= $escaper->escapeHtml(__('ZIP/CEP')) ?></label>
        <input type="text" class="input-text cep" placeholder="<?= __("Enter your ZIP code") ?>" />
        <button type="button" class="action primary estimate">
            <span><?= $escaper->escapeHtml(__('Estimate')) ?></span>
        </button>

    </div>
    <a class="shipping-help" target="_blank" href="https://buscacepinter.correios.com.br/app/endereco/index.php"><?= __('Forgot my ZIP code'); ?></a>


    <div class="results" style="margin-top:10px;"></div>
</div>


<script type="text/x-magento-init">
    {
        ".shipping-estimator": {
            "Avanti_ShippingEstimator/js/estimator": {}
        }
    }
</script>
