<?php
/** @var \Magento\Catalog\Block\Product\View\Details $block */
?>
<div class="product-details-columns">
    <h1 class="title-header"><?= __('details') ?></h1>
    <div class="product-details-columns__col product-details-columns__col--left">
        <?= $block->getChildHtml('description') ?>
    </div>

    <h1 class="title-header"><?= __('More information') ?></h1>
    <div class="product-details-columns__col product-details-columns__col--right">
        <?= $block->getChildHtml('additional') ?>
    </div>
</div>
