<div class="product-details-columns-wrapper">
<div class="product-details-columns">

    <div class="product-details-columns__col product-details-columns__col--left">
        <h1 class="title-header"><?= __('Details') ?></h1>
        <?= $block->getChildHtml('description') ?>
    </div>


    <div class="product-details-columns__col product-details-columns__col--right">
        <h1 class="title-header"><?= __('More information') ?></h1>
        <?= $block->getChildHtml('additional') ?>
    </div>
</div>
</div>
